### Test trip - Expected isInteresting: false
POST https://tripanalyzerfunc-hpdmcwa4gda2h5ar.canadacentral-01.azurewebsites.net/api/trip
Content-Type: application/json

{
  "ContentData": {
    "vendorID": "asdasd",
    "tripDistance": 15,
    "passengerCount": 2,
    "paymentType": "1"
  }
}


